name: COLD-Attack
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - argon2-cffi-bindings=21.2.0
  - async-lru=2.0.4
  - attrs=24.3.0
  - beautifulsoup4=4.12.3
  - bleach=6.2.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - decorator=5.1.1
  - defusedxml=0.7.1
  - h11=0.14.0
  - ipykernel=6.29.5
  - jedi=0.19.2
  - jsonschema=4.23.0
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.3.4
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.27.3
  - libffi=3.4.4
  - libsodium=1.0.18
  - nbconvert=7.16.4
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - notebook=7.3.2
  - openssl=3.0.15
  - parso=0.8.4
  - pip=24.2
  - prometheus_client=0.21.0
  - prompt_toolkit=3.0.43
  - pure_eval=0.2.2
  - pysocks=1.7.1
  - python=3.11.10
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=3.2.1
  - pytz=2024.1
  - pyzmq=26.2.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tk=8.6.14
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - websocket-client=1.8.0
  - wheel=0.44.0
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - pip:
      - accelerate==0.28.0
      - annotated-types==0.7.0
      - anyio==4.7.0
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - babel==2.16.0
      - bitsandbytes==0.45.0
      - boto3==1.35.90
      - botocore==1.35.90
      - certifi==2024.2.2
      - click==8.1.7
      - comm==0.2.2
      - contourpy==1.2.0
      - cycler==0.12.1
      - debugpy==1.8.11
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - executing==2.1.0
      - fastjsonschema==2.21.1
      - filelock==3.13.1
      - fonttools==4.50.0
      - fqdn==1.5.1
      - fsspec==2024.3.1
      - gitdb==4.0.11
      - gitpython==3.1.42
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.27.1
      - idna==3.6
      - ipython==8.31.0
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jinja2==3.1.3
      - jiter==0.8.2
      - jmespath==1.0.1
      - joblib==1.3.2
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema-specifications==2024.10.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-events==0.11.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab-pygments==0.3.0
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.5
      - markupsafe==2.1.5
      - matplotlib==3.8.3
      - matplotlib-inline==0.1.7
      - mistune==3.0.2
      - modelscope==1.21.1
      - mpmath==1.3.0
      - nbclient==0.10.2
      - networkx==3.2.1
      - nltk==3.8.1
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - ollama==0.4.7
      - openai==1.63.0
      - overrides==7.7.0
      - packaging==24.0
      - pandas==2.2.1
      - pandocfilters==1.5.1
      - peft==0.14.0
      - pillow==10.2.0
      - platformdirs==4.3.6
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.48
      - protobuf==4.25.3
      - psutil==5.9.8
      - pure-eval==0.2.3
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygments==2.18.0
      - pyparsing==3.1.2
      - pyyaml==6.0.1
      - referencing==0.35.1
      - regex==2023.12.25
      - requests==2.31.0
      - rpds-py==0.22.3
      - s3transfer==0.10.4
      - safetensors==0.4.2
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sentencepiece==0.2.0
      - sentry-sdk==2.22.0
      - setproctitle==1.3.3
      - setuptools==69.2.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - sympy==1.13.1
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tinycss2==1.4.0
      - tokenizers==0.21.0
      - tqdm==4.66.2
      - transformers==4.47.1
      - types-python-dateutil==2.9.0.20241206
      - tzdata==2024.1
      - uri-template==1.3.0
      - urllib3==2.2.1
      - wandb==0.16.4
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - widgetsnbextension==4.0.13
